apiVersion: v1
kind: Service
metadata:
  name: tictac-service-svc
  namespace: im-test
spec:
  ports:
    -
      nodePort: 61298
      port: 8080
  selector:
    app: tictac-service
  type: NodePort